* *   Problem 1

   If we list all the natural numbers below 10 that are multiples of 3 or 5,
   we get 3, 5, 6 and 9. The sum of these multiples is 23.

   Find the sum of all the multiples of 3 or 5 below 1000.

   Project Euler: Copyright Information | Privacy Policy

   The page has been left unattended for too long and that link/button is no
   longer active. Please refresh the page.
   Project Euler
      Search Problems   RSS Feed
   [ ]
     * About
     * Archives
     * Recent
     * News
     * Register
     * Sign In
   projecteuler.net

Multiples of 3 or 5

   Show HTML problem content Published on Friday, 5th October 2001, 06:00 pm;
   Solved by 969527;
   Difficulty rating: 5%

  Problem 1

   If we list all the natural numbers below 10 that are multiples of 3 or 5,
   we get 3, 5, 6 and 9. The sum of these multiples is 23.

   Find the sum of all the multiples of 3 or 5 below 1000.

   Project Euler: Copyright Information | Privacy Policy

   The page has been left unattended for too long and that link/button is no
   longer active. Please refresh the page.
